export default {
  SF_UPDATION_STATUS: {
    NEW: 'NEW',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    DUPLICATE: 'DUPLICATE',
    REJECTED: 'REJECTED',
  },
  JOB_TYPE: {
    MOVEOUT: 'MOVEOUT',
    RENEWALS: 'RENEWALS',
  },
};
